# accept self-signed SSL certs for backends
InsecureSkipVerify = true

defaultEntryPoints = ["http", "https"]

[acme]
email = "hostmaster@klink.asia"
storage = "cert/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "klink.asia"
watch = true
exposedbydefault = false

# new domains and subdomains can be configured here.
# note that domains and subdomains not defined in this file will still work,
# when defined in a container Host-Rule. However, they will generate
# their own ACME request, and will count towards LetsEncrypt's rate limit.
#[[acme.domains]]
#  main = "klink.asia"
#  sans = [
#    # services
#    "mumble.klink.asia",
#    # ...
#
#    # web vhosts:
#    "www.klink.asia",
#    "git.klink.asia",
#    "docker.klink.asia",
#    "chat.klink.asia",
#  ]

# You can define multiple of these blocks, each of which will result in one
# certificate.
#[[acme.domains]]
#  main = "oneofftech.xyz"
#  sans = ["www.oneofftech.xyz", "mail.oneofftech.xyz"]


